// generated by Fast Light User Interface Designer (fluid) version 1.0103

#ifndef testflews_h
#define testflews_h
#include <FL/Fl.H>
#include <FL/Fl_flews.h>
#include <FL/Fl_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#endif
